//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmasOrders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int BatchID { get; set; }
        public int UserID { get; set; }
        public int CatalogID { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime AddDate { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual User User { get; set; }
        public virtual OrderBatch OrderBatch { get; set; }
    }
}
