//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmasOrders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBatch
    {
        public OrderBatch()
        {
            this.Catalogs = new HashSet<Catalog>();
            this.Orders = new HashSet<Order>();
        }
    
        public int BatchID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual ICollection<Catalog> Catalogs { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
